/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university;

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class Student extends javax.swing.JDialog {

    /**
     * Creates new form Student
     */
    public static Connection con;
    public static int stdId;

    public Student(java.awt.Frame parent, boolean modal,
            Connection con, int stdId) {
        super(parent, modal);
        initComponents();
        setTitle("Student form");
        setLocationRelativeTo(this);
        this.con = con;
        this.stdId = stdId;
        if (stdId > 0) {
            populate();
        }
    }

    public void populate() {
        try {
            PreparedStatement pstmt
                    = con.prepareStatement(
                            "Select * From tbluniversity "
                            + "where stdId = ?");
            pstmt.setInt(1, stdId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                txtFirstName.setText(rs.getString(2));
                txtLastName.setText(rs.getString(3));
                String gender = rs.getString(4);
                if(gender.equals("Male")){
                    rbMale.setSelected(true);
                }else{
                    rbFemale.setSelected(true);
                }
                txtAcademicYear.setText(
                        String.valueOf(rs.getInt(5)));
                boolean lebanese = rs.getBoolean(6);
                if(lebanese){
                    chkLebanese.setSelected(true);
                }
                txtEmail.setText(rs.getString(7));
                txtAddress.setText(rs.getString(8));
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        chkLebanese = new javax.swing.JCheckBox();
        txtAcademicYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });

        jLabel3.setText("Gender");

        rbgGender.add(rbMale);
        rbMale.setSelected(true);
        rbMale.setText("Male");

        rbgGender.add(rbFemale);
        rbFemale.setText("Female");

        jLabel4.setText("Academic Year");

        chkLebanese.setSelected(true);
        chkLebanese.setText("Lebanese");

        txtAcademicYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAcademicYearKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAcademicYearKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcademicYearKeyTyped(evt);
            }
        });

        jLabel6.setText("Email");

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel7.setText("Address");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtAddress);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)
                                .addComponent(rbMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFemale))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkLebanese)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAcademicYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLebanese)
                    .addComponent(txtAcademicYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        if (txtFirstName.getText().length() > 49) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        if (txtLastName.getText().length() > 49) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtAcademicYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcademicYearKeyTyped
        System.out.println(txtAcademicYear.getText().length());
        if ((txtAcademicYear.getText().length() > 0)
                || (!Character.isDigit(evt.getKeyChar()))
                || (Integer.parseInt(
                        String.valueOf(evt.getKeyChar())) > 4)
                || (Integer.parseInt(
                        String.valueOf(evt.getKeyChar())) == 0)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAcademicYearKeyTyped

    private void txtAcademicYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcademicYearKeyReleased

    }//GEN-LAST:event_txtAcademicYearKeyReleased

    private void txtAcademicYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcademicYearKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcademicYearKeyPressed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if (txtEmail.getText().length() > 99) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        if (txtAddress.getText().length() > 199) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAddressKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(txtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill first name",
                    "Missing entry", JOptionPane.WARNING_MESSAGE);
        }else if(txtLastName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill last name",
                    "Missing entry", JOptionPane.WARNING_MESSAGE);
        }else if(txtAcademicYear.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill academic year",
                    "Missing entry", JOptionPane.WARNING_MESSAGE);
        }else{
            String firstName = txtFirstName.getText();
            String lastName = txtLastName.getText();
            String gender;
            if(rbMale.isSelected()){
                gender = "Male";
            }else{
                gender = "Female";
            }
            boolean lebanese = chkLebanese.isSelected();
            int academicYear = Integer.parseInt(txtAcademicYear.getText().toString());
            String email = txtEmail.getText();
            String address = txtAddress.getText();
            try{
                Statement stmt = con.createStatement();
                if(stdId==0){
                    stmt.execute("Insert into "
                            + "tbluniversity (stdFirstName, "
                            + "stdLastName,"
                            + "stdGender, stdAcademicYear, "
                            + "stdLebanese, stdEmail, stdAddress) "
                            + "values ('"+ firstName +"', "
                            + "'"+ lastName +"', "
                            + "'"+ gender +"', "
                            + academicYear +", "
                            + lebanese +", "
                            + "'"+ email +"', "
                            + "'"+ address +"')");
                }else{
                    stmt.execute("Update tbluniversity set "
                            + "stdFirstName = '" + firstName + "',"
                            + "stdLastName = '" + lastName + "',"
                            + "stdGender = '" + gender + "',"
                            + "stdAcademicYear = " + academicYear + ","
                            + "stdLebanese = " + lebanese + ","
                            + "stdEmail = '" + email + "',"
                            + "stdAddress = '" + address + "' "
                            + "where stdId = " + stdId);
                }
                this.dispose();
            }catch(SQLException ex){
                System.err.println(ex.getMessage());
            }
        }
    
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Student dialog = new Student(new javax.swing.JFrame(), true, con, stdId);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkLebanese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.ButtonGroup rbgGender;
    private javax.swing.JTextField txtAcademicYear;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
